# Generated by Django 5.0.1 on 2024-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourism/images/')),
                ('area_found', models.TextField()),
                ('distance_from_addis', models.CharField(max_length=100)),
            ],
        ),
    ]
