# Generated by Django 5.0.1 on 2024-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tourismspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismspot',
            name='area_found',
            field=models.CharField(max_length=100),
        ),
    ]
